export enum PaymentStatus{
    CANCELLED = 'CANCELLED',
    EXPIRED = 'EXPIRED',
    NEEDS_ATTENTION = 'NEEDS_ATTENTION',
    OPEN='OPEN',
    OVERCHARGED='OVERCHARGED',
    PENDING_APPROVAL='PENDING_APPROVAL',
    RECONCILED='RECONCILED',
    UNDERCHARGED='UNDERCHARGED'
}